INSERT INTO hobbies (id, name, user_id)
VALUES ('1', 'Reading', '1'),
       ('2', 'Cooking', '1'),
       ('3', 'Hiking', '2'),
       ('4', 'Painting', '2'),
       ('5', 'Gardening', '2'),
       ('6', 'Playing Guitar', '3'),
       ('7', 'Photography', '3'),
       ('8', 'Knitting', '4'),
       ('9', 'Cycling', '4'),
       ('10', 'Drawing', '5'),
       ('11', 'Writing', '5'),
       ('12', 'Yoga', '5'),
       ('13', 'Fishing', '6'),
       ('14', 'Traveling', '6'),
       ('15', 'Skiing', '7'),
       ('16', 'Dancing', '7'),
       ('17', 'Swimming', '8'),
       ('18', 'Singing', '8'),
       ('19', 'Running', '9'),
       ('20', 'Mediation', '9'),
       ('21', 'Chess', '10'),
       ('22', 'Soccer', '10'),
       ('23', 'Basketball', '11'),
       ('24', 'Boxing', '11'),
       ('25', 'Surfing', '12');
