INSERT INTO users (id, username, age)
VALUES ('3', 'Michael Johnson', 35),
       ('4', 'Emily Davis', 28),
       ('5', 'William Wilson', 31),
       ('6', 'Sophia Martinez', 24),
       ('7', 'Daniel Anderson', 29),
       ('8', 'Isabella Taylor', 27),
       ('9', 'Christopher Thomas', 33),
       ('10', 'Emma Lopez', 26),
       ('11', 'Matthew Hernandez', 30),
       ('12', 'Olivia Lee', 32),
       ('13', 'James Gonzalez', 34),
       ('14', 'Ava Perez', 25),
       ('15', 'John Wilson', 36),
       ('16', 'Madison Moore', 29),
       ('17', 'David Jackson', 31),
       ('18', 'Sophia White', 27),
       ('19', 'Joseph Harris', 28),
       ('20', 'Chloe Martin', 30),
       ('21', 'Daniel Young', 33),
       ('22', 'Abigail King', 32),
       ('23', 'Ethan Wright', 35),
       ('24', 'Emily Green', 26),
       ('25', 'Alexander Rodriguez', 29),
       ('26', 'Mia Hill', 31);
